# Generated by Django 4.1 on 2022-09-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_userimg_alter_blogs_activeuser_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blogimage',
            field=models.ImageField(default=0, upload_to='blog_img'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='relatedfile',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
