# Generated by Django 4.1 on 2022-09-03 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0005_alter_blogs_blogimage_alter_blogs_relatedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='activeuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
